<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace Defaults\Core\Models\Orm\Auth\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractUserTracking
* @package Core\Models\Orm\Auth\AbstractModels
*
* @property bigInteger $id
* @property bigInteger $userId
* @property string $userAgent
* @property boolean $verified
* @property enum $verifiedBy
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \Core\Models\Orm\Auth\User|null $user
*/ 
abstract class AbstractUserTracking extends Model
{
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'userId' => 'integer',
        'userAgent' => 'string',
        'verified' => 'boolean',
        'verifiedBy' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
    
    public function user()
    {
        return $this->belongsTo('\Core\Models\Orm\Auth\User', 'userId', 'id');
    }
}
