<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 5ae3e8a2-43b9-4055-90ea-55279a783a0a
 * Migration local datetime: 2026-01-29 11:18:20.353042
 * Migration UTC datetime: 2026-01-29 11:18:20.353042
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2026012911182035 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('name', 255)->nullable(true);
            $table->string('email', 255)->nullable(true);
            $table->string('password', 255)->nullable(true);
            $table->string('mobile', 255)->nullable(true);
            $table->string('admin', 255)->nullable(true);
            $table->timestamp('lastLogin')->default('0000-00-00 00:00:00');
            $table->bigInteger('userLegalId')->nullable(true)->unsigned();
            $table->boolean('verified')->nullable(true);
            $table->enum('verifiedMethod', ['EMAIL'])->nullable(true);
            $table->timestamp('verifiedTime')->nullable(true);
            $table->string('forgotPassword')->nullable(true);
            $table->string('forgotPasswordTime')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('logs', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('userId')->nullable(true)->unsigned();
            $table->enum('action', ['login', 'logout', 'create', 'delete', 'view','update'])->nullable(true);
            $table->text('message')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('legals', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('document')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('trackings', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('userId')->nullable(true)->unsigned();
            $table->string('userAgent')->nullable(true);
            $table->boolean('verified')->nullable(true);
            $table->enum('verifiedBy', ['email', 'sms', 'whatsapp',  'authenticator', 'telegram'])->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('verifieds', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('userId')->nullable(true)->unsigned();
            $table->enum('method', ['SMS', 'Email', 'WhatsApp', 'Telegram'])->nullable(true);
            $table->boolean('verified')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::table('users', function (Blueprint $table) {
            $table->foreign('userLegalId')->references('id')->on('legals');
        });
        Schema::table('logs', function (Blueprint $table) {
            $table->foreign('userId')->references('id')->on('users');
        });
        Schema::table('trackings', function (Blueprint $table) {
            $table->foreign('userId')->references('id')->on('users');
        });
        Schema::table('verifieds', function (Blueprint $table) {
            $table->foreign('userId')->references('id')->on('users');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('verifieds')) {
            Schema::table('verifieds', function (Blueprint $table) {
                $table->dropForeign(['userId']);
            });
        }
        if (Schema::hasTable('trackings')) {
            Schema::table('trackings', function (Blueprint $table) {
                $table->dropForeign(['userId']);
            });
        }
        if (Schema::hasTable('logs')) {
            Schema::table('logs', function (Blueprint $table) {
                $table->dropForeign(['userId']);
            });
        }
        if (Schema::hasTable('users')) {
            Schema::table('users', function (Blueprint $table) {
                $table->dropForeign(['userLegalId']);
            });
        }
        Schema::dropIfExists('verifieds');
        Schema::dropIfExists('trackings');
        Schema::dropIfExists('legals');
        Schema::dropIfExists('logs');
        Schema::dropIfExists('users');
    }
}
