<?php
namespace YoudsFramework\Config;
use YoudsFramework\Request\ParameterHolder;
use YoudsFramework\Util\Toolkit;

// +----------------------------------------------------------------------------+
// | This file is part of the Youds Framework package.                         	|
// | Copyright (c) Youds Media Limited; see https://framework.youds.com			|
// |                                                                           	|
// | For the full copyright and license information, please view the LICENSE 	|
// | file that was distributed with this source code. 							|
// +----------------------------------------------------------------------------+

/**
 * BaseHandler allows a developer to create a custom formatted
 * configuration file pertaining to any information they like and still
 * have it auto-generate PHP code.
 *
 * @package    Youds Framework - https://framework.youds.com
 *
 * @author     Sean Kerr <skerr@mojavi.org>
 * @author     Dominik del Bondio <ddb@bitxtender.com>
 * @author     David Zülke <dz@bitxtender.com>
 *
 * @since      0.1
 *
 * @version    $Id$
 */
abstract class BaseHandler extends ParameterHolder
{
	/**
	 * Generate the code for returning from execute().
	 *
	 * @param      mixed A string with the code, or an array of code lines.
	 * @param      string An optional config file path, to be put in a comment.
	 *
	 * @return     string PHP code.
	 *
	 * @author     David Zülke <dz@bitxtender.com>
	 */
	protected function generate($code, $path = null)
	{
		if(is_array($code)) {
			$code = implode("\n", $code);
		}
		 
		return sprintf(
			"<?php\n\nnamespace YoudsFramework;\n\n// This is a compiled Youds Framework configuration file\n// Compiled from: %s\n// Generated by: %s\n// Date: %s\n\n%s\n\n?>",
			$path === null ? '(unknown)' : $path,
			get_class($this),
			gmdate(DATE_ISO8601),
			$code
		);
	}
	
	/**
	 * Literalize a string value.
	 *
	 * @param      string The value to literalize.
	 *
	 * @return     string A literalized value.
	 *
	 * @author     Sean Kerr <skerr@mojavi.org>
	 * @author     Dominik del Bondio <ddb@bitxtender.com>
	 * @author     David Zülke <dz@bitxtender.com>
	 *
	 * @deprecated Use Toolkit::expandDirectives() instead.
	 */
	public static function literalize($value)
	{
		return Toolkit::literalize($value);
	}

	/**
	 * Replace configuration directive identifiers in a string.
	 *
	 * @param      string The value on which to run the replacement procedure.
	 *
	 * @return     string The new value.
	 *
	 * @author     Sean Kerr <skerr@mojavi.org>
	 * @author     Johan Mjones <johan.mjones@ongame.com>
	 * @author     David Zülke <dz@bitxtender.com>
	 *
	 * @deprecated Use Toolkit::expandDirectives() instead.
	 */
	public static function replaceConstants($value)
	{
		return Toolkit::expandDirectives($value);
	}

	/**
	 * Replace a relative filesystem path with an absolute one.
	 *
	 * @param      string A relative filesystem path.
	 *
	 * @return     string The new path.
	 *
	 * @author     Sean Kerr <skerr@mojavi.org>
	 */
	public static function replacePath($path)
	{
		if(!Toolkit::isPathAbsolute($path)) {
			// not an absolute path so we'll prepend to it
			$path = Config::get('core.app_dir') . '/' . $path;
		}

		return $path;
	}
}

?>
