<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace Core\Models\Orm\Auth\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractUserLegal
* @package Core\Models\Orm\Auth\AbstractModels
*
* @property bigInteger $id
* @property string $document
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \Illuminate\Database\Eloquent\Collection $users
*/ 
abstract class AbstractUserLegal extends Model
{
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'document' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
    
    public function users()
    {
        return $this->hasMany('\Core\Models\Orm\Auth\User', 'userLegalId', 'id');
    }
}
