<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace Core\Models\Orm\Auth\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractUser
* @package Core\Models\Orm\Auth\AbstractModels
*
* @property bigInteger $id
* @property string $name
* @property string $email
* @property string $password
* @property string $mobile
* @property string $admin
* @property \Carbon\Carbon $lastLogin
* @property bigInteger $userLegalId
* @property boolean $verified
* @property enum $verifiedMethod
* @property \Carbon\Carbon $verifiedTime
* @property string $forgotPassword
* @property string $forgotPasswordTime
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \Core\Models\Orm\Auth\User\Legal|null $userLegal
* @property \Illuminate\Database\Eloquent\Collection $userLogs
* @property \Illuminate\Database\Eloquent\Collection $userTrackings
* @property \Illuminate\Database\Eloquent\Collection $verifieds
*/ 
abstract class AbstractUser extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'users';
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = ['lastLogin' => ''0000-00-00 00:00:00''];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'email' => 'string',
        'password' => 'string',
        'mobile' => 'string',
        'admin' => 'string',
        'lastLogin' => 'datetime',
        'userLegalId' => 'integer',
        'verified' => 'boolean',
        'verifiedMethod' => 'string',
        'verifiedTime' => 'datetime',
        'forgotPassword' => 'string',
        'forgotPasswordTime' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
    
    public function userLegal()
    {
        return $this->belongsTo('\Core\Models\Orm\Auth\User\Legal', 'userLegalId', 'id');
    }
    
    public function userLogs()
    {
        return $this->hasMany('\Core\Models\Orm\Auth\User\Log', 'userId', 'id');
    }
    
    public function userTrackings()
    {
        return $this->hasMany('\Core\Models\Orm\Auth\User\Tracking', 'userId', 'id');
    }
    
    public function verifieds()
    {
        return $this->hasMany('\Core\Models\Orm\Auth\User\Verified', 'userId', 'id');
    }
}
